wcs_terrain:
    resource: "@WCSTerrainBundle/Resources/config/routing.yml"
    prefix:   /

wcs_fly:
    resource: "@WCSFlyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
